### ISSUE TITLE
v3 - roadmap

### ISSUE THREAD

**Issue by Arenukvern** [xsoulspace/last_answer#40]
## App Sections & Features:
- [x] Projects
- [x] Idea
- [x] Note
- [x] Settings
- [x] Mobile layout
- [x] Basic Desktop layout
- [x] Advanced Desktop layout
- [x] Universal Light / Dark theme switching
- [x] Localisation English
- [x] Localisation Russian
- [x] Localisation Italian
- [x] Localisation cleanup
- [x] #39 
- [x] #37
- [x] Project autosave
- [x] Project autosave indicators & animations
- [x] Material theme text adaptation
- [x] Idea answer input text and question autosave
- [x] Project removal dialog
- [x] Data migration
- [x] Behaviour dependent keyboard appearance 
- [x] Idea Sharer
- [x] Note Sharer
- [x] List of  Emoji for idea answer
- [x] List of  Emoji fore note
- [x] Emoji search
- [x] Special Emojis
- [x] Reorderable projects list
- [x] Update notification system (maybe as readonly note bubbles)

## Project menu: 
- [x] Delete
- [x] Note: length limits?

## Desktop themes:
For transparency use https://github.com/alexmercerind/flutter_acrylic

- [x] Transparent theme for MacOS
- [ ] Transparent theme for Linux (postponed)
- [ ] Transparent theme for Windows (postponed)
- [ ] Color themes? (Personalisation) (postponed)

## Roadmap:
- [x] Figma design mobile light version
- [x] Figma design mobile dark version
- [ ] Figma design desktop light version (don't needed)
- [ ] Figma design desktop dark version (don't needed)
- [x] Idea Prototype 
- [x] Data migration
- [x] Note Prototype
- [x] Edge version in Snapstore
- [x] Desktop layout
- [x] Edge version in Snapstore
- [x] Emoji desktop integration
- [x] Edge version in Snapstore
- [x] Release Google Play
- [x] Feature/Bugs closures
- [x] Edge version in Snapstore
- [x] Meta update
- [x] Screenshots update
- [x] Feature/Bugs closures 
- [x] Release Snap Store
- [x] Release Apple Store
